### PR TITLE
Add Gnome 45 support

### LINKED ISSUE #15: Port extension to GNOME 45
Under GNOME 45 the extension does not work.
It would be much appreciated if someone could change that.
Thanks in advance!

### PR DESCRIPTION
**Pull request by zumoshi**
fixes #15

More info:
- https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/
- https://gjs.guide/extensions/upgrading/gnome-shell-45.html

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Are notifications working for you ? i tried the patch, and got the panel to move, but notifications stops working.
I see lots of this in log :
```
JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0
```

**Comment by gilesfun** [comment]
Notifications broken for me too, using the below extension works as a quick fix:

https://github.com/soal/gnome-shell-extension-fullscreen-notifications

**Comment by zumoshi** [comment]
My bad. I was following the official guide for migration and that didn't cover the tricks this extension used for working around lack of access to captured closure of original context of the monkey patched functions after doing search and replace in their code's text.

it should be fixed now. let me know if you noticed another issue.

**Comment by RaphaelRochet** [comment]
Awesome. Great work :+1:

**Comment by Noobsai** [comment]
@zumoshi, merged. Not fully tested from my side. But thanks a lot anyway!

**Pull request merged**
